#####################################################################
#
# DISCLAIMER: This script was generated by an LLM (Claude Haiku 4.5)
#
#####################################################################

import csv
import sys


def extract_npm_target_packages(csv_file):
    """
    Extract the 'target_package' column from a CSV file
    where ecosystem equals 'npm'.

    Args:
        csv_file (str): Path to the CSV file

    Returns:
        list: List of target packages for npm ecosystem
    """
    target_packages = []

    try:
        with open(csv_file, "r", encoding="utf-8") as file:
            reader = csv.DictReader(file)

            # Verify required columns exist
            if reader.fieldnames is None:
                print("Error: CSV file is empty or invalid", file=sys.stderr)
                return target_packages

            required_columns = {"target_package", "ecosystem"}
            if not required_columns.issubset(set(reader.fieldnames)):
                print(
                    f"Error: CSV must contain columns: {required_columns}",
                    file=sys.stderr,
                )
                return target_packages

            # Extract target_package where ecosystem is 'npm'
            for row in reader:
                if row.get("ecosystem", "").strip().lower() == "npm":
                    package = row.get("target_package", "").strip()
                    if (
                        package and package not in target_packages
                    ):  # Only add non-empty values and avoid duplicates
                        target_packages.append(package)

    except FileNotFoundError:
        print(f"Error: File '{csv_file}' not found", file=sys.stderr)
    except Exception as e:
        print(f"Error reading CSV file: {e}", file=sys.stderr)

    return target_packages


def main():
    if len(sys.argv) < 2:
        print("Usage: python extract_npm_packages.py <csv_file> [output_file]")
        print("\nExample:")
        print("  python extract_npm_packages.py data.csv")
        print("  python extract_npm_packages.py data.csv output.txt")
        sys.exit(1)

    csv_file = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) > 2 else None

    # Extract packages
    packages = extract_npm_target_packages(csv_file)

    if not packages:
        print("No npm packages found in the CSV file.")
        sys.exit(0)

    # Output results
    if output_file:
        try:
            with open(output_file, "w", encoding="utf-8") as f:
                for package in packages:
                    f.write(f"{package}\n")
            print(f"Extracted {len(packages)} npm packages to '{output_file}'")
        except Exception as e:
            print(f"Error writing to output file: {e}", file=sys.stderr)
            sys.exit(1)
    else:
        print(f"Found {len(packages)} npm packages:\n")
        for package in packages:
            print(package)


if __name__ == "__main__":
    main()
